-- =============================================================================
-- Colors & Hyprbars (hyprland/colors.conf → Lua)
-- Generated by matugen from Material You palette
-- NOTE: Hyprland 0.55+ required for Lua config
--
-- Dùng chuỗi rgba() — Lua number 0x00…… bị cắt byte cao.
-- Plugin hyprbars chỉ set khi đã load (tránh unknown config key).
-- =============================================================================

local function plugin_is_loaded(needle)
    local ok, plugins = pcall(function() return hl.get_loaded_plugins() end)
    if not ok or type(plugins) ~= "table" then return false end
    local n = needle:lower()
    for _, p in pairs(plugins) do
        local name = type(p) == "table" and (p.name or p.handle or p.path or "") or tostring(p)
        if type(name) == "string" and name:lower():find(n, 1, true) then
            return true
        end
    end
    return false
end

hl.config({
    misc = {
        background_color = "rgba({{colors.surface.dark.hex_stripped}}FF)",
    },
})

local function apply_hyprbars_config()
    if not plugin_is_loaded("hyprbars") then return false end

    hl.config({
        plugin = {
            hyprbars = {
                bar_text_font    = "Rubik, Geist, AR One Sans, Reddit Sans, Inter, Roboto, Ubuntu, Noto Sans, sans-serif",
                bar_height       = 30,
                bar_padding      = 10,
                bar_button_padding = 5,
                bar_precedence_over_border = true,
                bar_part_of_window = true,
                bar_color        = "rgba({{colors.surface_container.dark.hex_stripped}}FF)",
                col              = { text = "rgba({{colors.on_surface.dark.hex_stripped}}FF)" },
            },
        },
    })

    local hb = hl.plugin and hl.plugin.hyprbars
    if hb and type(hb.add_button) == "function" then
        local btn = "rgb({{colors.on_surface.dark.hex_stripped}})"
        hb.add_button({ bg_color = btn, size = 13, icon = "󰖭", action = "hyprctl dispatch killactive" })
        hb.add_button({ bg_color = btn, size = 13, icon = "󰖯", action = "hyprctl dispatch fullscreen 1" })
        hb.add_button({ bg_color = btn, size = 13, icon = "󰖰", action = "hyprctl dispatch movetoworkspacesilent special" })
    end
    return true
end

if not apply_hyprbars_config() then
    hl.on("hyprland.start", function()
        hl.timer(function()
            apply_hyprbars_config()
        end, { timeout = 2500, type = "oneshot" })
    end)
end

hl.window_rule({
    name  = "pin-border",
    match = { pin = true },
    border_color = {
        colors = {
            "rgba({{colors.primary.default.hex_stripped}}aa)",
            "rgba({{colors.primary.default.hex_stripped}}77)",
        },
    },
})
