# general {
#     col.active_border = rgba({{colors.outline.default.hex_stripped}}AA)
#     col.inactive_border = rgba({{colors.outline_variant.default.hex_stripped}}AA)
# }

misc {
    background_color = rgba({{colors.surface.dark.hex_stripped}}FF)
}

windowrulev3 = bordercolor rgba({{colors.primary.default.hex_stripped}}AA) rgba({{colors.primary.default.hex_stripped}}77),pinned:1
