-- =============================================================================
-- Colors & Hyprbars Configuration
-- Generated by matugen from Material You palette
-- =============================================================================

hl.config({
    misc = {
        -- Dark background for OLED displays
        background_color = 0x{{colors.surface.dark.hex_stripped}}FF,
    },
})

-- Pinned window border glow (primary accent color)
hl.window_rule({
    name = "pin-border",
    match = { pinned = true },
    bordercolor = { colors = {0x{{colors.primary.default.hex_stripped}}AA, 0x{{colors.primary.default.hex_stripped}}77} },
})

-- =============================================================================
-- Preset Floating Sizes (exported for use in rules.lua)
-- =============================================================================
-- These define common floating window sizes and positions for easy reuse
local fp = {
    center_45x45   = { size = { 0.45, 0.45 } },
    center_45x55   = { size = { 0.45, 0.55 } },
    center_55x70   = { size = { 0.55, 0.70 } },
    center_60x65   = { size = { 0.60, 0.65 } },
    top_right      = { size = { 0.20, 0.50 }, move = { 0.795, 0.04 } },
    bottom_right   = { size = { 0.20, 0.50 }, move = { 0.795, 0.49 } },
}

return fp  -- export for use in rules.lua