-- Generated by nwg-displays on 2026-08-18 at 19:02:40. Do not edit manually.

hl.monitor({
    output = "eDP-1",
    mode = "1920x1200@120.0",
    position = "1080x1080",
    scale = 1.0,
    bitdepth = 10
})
hl.monitor({
    output = "DP-1",
    mode = "1920x1080@60.0",
    position = "0x0",
    scale = 1,
    bitdepth = 10,
    transform = 3
})
hl.monitor({
    output = "HDMI-A-1",
    mode = "1920x1080@74.97",
    position = "1080x0",
    scale = 1,
    bitdepth = 10
})
