-- Generated by nwg-displays on 2026-07-20 at 23:32:40. Do not edit manually.

hl.monitor({
    output = "eDP-1",
    mode = "1920x1200@120.0",
    position = "1920x0",
    scale = 1.0,
    bitdepth = 10
})
hl.monitor({
    output = "HDMI-A-1",
    mode = "1920x1080@74.97",
    position = "0x0",
    scale = 1.0,
    bitdepth = 10
})
