-- Generated by nwg-displays (format). Do not edit manually.
-- nwg-displays ghi đè file này khi bấm Apply trong tab Workspaces.

hl.workspace_rule({
    workspace = "1",
    monitor = "eDP-1",
    default = true
})
hl.workspace_rule({
    workspace = "2",
    monitor = "eDP-1"
})
hl.workspace_rule({
    workspace = "3",
    monitor = "eDP-1"
})
hl.workspace_rule({
    workspace = "4",
    monitor = "eDP-1"
})
hl.workspace_rule({
    workspace = "5",
    monitor = "eDP-1"
})
hl.workspace_rule({
    workspace = "6",
    monitor = "eDP-1"
})
hl.workspace_rule({
    workspace = "7",
    monitor = "eDP-1"
})
hl.workspace_rule({
    workspace = "8",
    monitor = "eDP-1"
})
hl.workspace_rule({
    workspace = "9",
    monitor = "eDP-1"
})
hl.workspace_rule({
    workspace = "10",
    monitor = "eDP-1"
})
hl.workspace_rule({
    workspace = "11",
    monitor = "HDMI-A-1",
    default = true
})
hl.workspace_rule({
    workspace = "12",
    monitor = "HDMI-A-1"
})
hl.workspace_rule({
    workspace = "13",
    monitor = "HDMI-A-1"
})
hl.workspace_rule({
    workspace = "14",
    monitor = "HDMI-A-1"
})
hl.workspace_rule({
    workspace = "15",
    monitor = "HDMI-A-1"
})
hl.workspace_rule({
    workspace = "16",
    monitor = "HDMI-A-1"
})
hl.workspace_rule({
    workspace = "17",
    monitor = "HDMI-A-1"
})
hl.workspace_rule({
    workspace = "18",
    monitor = "HDMI-A-1"
})
hl.workspace_rule({
    workspace = "19",
    monitor = "HDMI-A-1"
})
hl.workspace_rule({
    workspace = "20",
    monitor = "HDMI-A-1"
})
