# Don't print a new line at the start of the prompt
add_newline = true
# Pipes ╰─ ╭─
# Powerline symbols                                     
# Wedges 🭧🭒 🭣🭧🭓
# Random noise 🬖🬥🬔🬗
# Cool stuff 󰜥   

# format = """
# $cmd_duration$username$hostname $directory $git_branch
# $character
# """
format = """
$localip\
$shlvl\
$singularity\
$kubernetes\
$directory\
$vcsh\
$fossil_branch\
$fossil_metrics\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$hg_branch\
$hg_state\
$pijul_channel\
$docker_context\
$package\
$c\
$cmake\
$cobol\
$daml\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$fennel\
$fortran\
$gleam\
$golang\
$guix_shell\
$haskell\
$haxe\
$helm\
$java\
$julia\
$kotlin\
$gradle\
$lua\
$nim\
$nodejs\
$ocaml\
$opa\
$perl\
$php\
$pulumi\
$purescript\
$python\
$pixi\
$quarto\
$raku\
$rlang\
$red\
$ruby\
$rust\
$scala\
$solidity\
$swift\
$terraform\
$typst\
$vlang\
$vagrant\
$zig\
$buf\
$nix_shell\
$conda\
$meson\
$spack\
$memory_usage\
$aws\
$gcloud\
$openstack\
$azure\
$nats\
$direnv\
$env_var\
$mise\
$crystal\
$custom\
$sudo\
$cmd_duration\
$line_break\
$jobs\
$battery\
$time\
$status\
$container\
$netns\
$shell\
$character"""

# Replace the "❯" symbol in the prompt with "➜"
[character]                            # The name of the module we are configuring is "character"
success_symbol = "[   ](bold fg:#50C878)"
error_symbol = "[   ](bold fg:red)"

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[git_branch]
style = "bg:#50C878"
symbol = "󰘬"
truncation_length = 12
truncation_symbol = ""
format = "󰜥 [](bold fg:#50C878)[$symbol $branch(:$remote_branch)](fg:black bg:#50C878)[ ](bold fg:#50C878)"

[git_commit]
commit_hash_length = 4
tag_symbol = " "

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '
cherry_pick = "[🍒 PICKING](bold red)"

[git_status]
conflicted = " 🏳 "
ahead = " 🏎💨 "
behind = " 😰 "
diverged = " 😵 "
untracked = " 🤷 ‍"
stashed = " 📦 "
modified = " 📝 "
staged = '[++\($count\)](green)'
renamed = " ✍️ "
deleted = " 🗑 "

[hostname]
ssh_only = false
format =  "[•$hostname](bg:#50C878 bold fg:black)[](bold fg:#50C878)"
trim_at = ".companyname.com"
disabled = false

[line_break]
disabled = false

[memory_usage]
disabled = true
threshold = -1
symbol = "󰍛 "
style = "bold dimmed green"

[time]
disabled = true
format = '🕙[\[ $time \]]($style) '
time_format = "%T"

[username]
style_user = "bold bg:#50C878 fg:black"
style_root = "red bold"
format = "[ ](bold fg:#50C878)[$user]($style)"
disabled = false
show_always = true

[directory]
home_symbol = "  "
read_only = "  "
style = "bg:#50C878 fg:black"
truncation_length = 6
truncation_symbol = " ••/"
format = '[ ](bold fg:#50C878)[󰉋 $path]($style)[ ](bold fg:#50C878)'

[directory.substitutions]
"Desktop" = "  "
"Documents" = "  "
"Downloads" = "  "
"Music" = " 󰎈 "
"Pictures" = "  "
"Videos" = "  "
"GitHub" = " 󰊤 "

[cmd_duration]
min_time = 0
format = '[](bold fg:yellow)[󰪢 $duration](bold bg:yellow fg:black)[](bold fg:yellow)'

[os]
disabled = false

[aws]
symbol = " "
style = "bold bright-yellow"

[buf]
symbol = " "
style = "bold bright-blue"

[bun]
symbol = " "
style = "bold bright-red"

[c]
symbol = " "
style = "bold bright-green"

[cpp]
symbol = " "
style = "bold bright-green"

[cmake]
symbol = " "
style = "bold bright-blue"

[conda]
symbol = " "
style = "bold bright-green"

[crystal]
symbol = " "
style = "bold bright-red"

[dart]
symbol = " "
style = "bold bright-blue"

[deno]
symbol = " "
style = "bold bright-green"

[docker_context]
symbol = " "
style = "bold bright-blue"

[elixir]
symbol = " "
style = "bold bright-purple"

[elm]
symbol = " "
style = "bold bright-cyan"

[fennel]
symbol = " "
style = "bold bright-green"

[fortran]
symbol = " "
style = "bold bright-purple"

[fossil_branch]
symbol = " "
style = "bold bright-purple"

[gcloud]
symbol = " "
style = "bold bright-blue"

[golang]
symbol = " "
style = "bold bright-cyan"

[gradle]
symbol = " "
style = "bold bright-cyan"

[guix_shell]
symbol = " "
style = "bold bright-yellow"

[haskell]
symbol = " "
style = "bold bright-purple"

[haxe]
symbol = " "
style = "bold fg:214"

[hg_branch]
symbol = " "
style = "bold bright-purple"


[java]
symbol = " "
style = "bold bright-red"

[julia]
symbol = " "
style = "bold bright-purple"

[kotlin]
symbol = " "
style = "bold bright-blue"

[lua]
symbol = " "
style = "bold bright-blue"

[meson]
symbol = "󰔷 "
style = "bold bright-blue"

[nim]
symbol = "󰆥 "
style = "bold bright-yellow"

[nix_shell]
symbol = " "
style = "bold bright-blue"

[nodejs]
symbol = " "
style = "bold bright-green"

[ocaml]
symbol = " "
style = "bold bright-yellow"

[os.symbols]
Alpaquita = " "
Alpine = " "
AlmaLinux = " "
Amazon = " "
Android = " "
AOSC = " "
Arch = " "
Artix = " "
CachyOS = " "
CentOS = " "
Debian = " "
DragonFly = " "
Elementary = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Ios = "󰀷 "
Kali = " "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
Nobara = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
RockyLinux = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Void = " "
Windows = "󰍲 "
Zorin = " "

[perl]
symbol = " "
style = "bold bright-green"

[php]
symbol = " "
style = "bold bright-purple"

[pijul_channel]
symbol = " "
style = "bold bright-purple"

[python]
symbol = " "
style = "bold bright-yellow"

[rlang]
symbol = "󰟔 "
style = "bold bright-blue"

[ruby]
symbol = " "
style = "bold bright-red"

[rust]
symbol = "󱘗 "
style = "bold bright-red"

[scala]
symbol = " "
style = "bold bright-red"

[status]
symbol = " "
style = "bold bright-red"

[swift]
symbol = " "
style = "bold 214"

[xmake]
symbol = " "
style = "bold bright-green"

[zig]
symbol = " "
style = "bold bright-yellow"
