# general {
#     col.active_border = rgba(8c919cAA)
#     col.inactive_border = rgba(424751AA)
# }

misc {
    background_color = rgba(0e141cFF)
}

windowrulev3 = bordercolor rgba(a6c8ffAA) rgba(a6c8ff77),pinned:1
