-- =============================================================================
-- Colors & Hyprbars (hyprland/colors.conf → Lua)
-- Generated by matugen from Material You palette
-- NOTE: Hyprland 0.55+ required for Lua config
--
-- Hyprbars: repeated `hyprbars-button` in hyprlang is NOT valid inside
-- hl.config plugin.hyprbars in Lua — use hl.plugin.hyprbars.add_button().
-- See: https://github.com/hyprwm/hyprland-plugins/blob/main/hyprbars/README.md
--
-- Pinned border: window rules use `border_color` (not `bordercolor`); gradient
-- colors should be strings (rgba/rgb/0x…), not raw Lua numbers.
-- =============================================================================

hl.config({
    misc = {
        background_color = 0x091517FF,
    },
    plugin = {
        hyprbars = {
            bar_text_font    = "Rubik, Geist, AR One Sans, Reddit Sans, Inter, Roboto, Ubuntu, Noto Sans, sans-serif",
            bar_height       = 30,
            bar_padding      = 10,
            bar_button_padding = 5,
            bar_precedence_over_border = true,
            bar_part_of_window = true,

            bar_color        = 0x111e1fFF,
            col              = { text = 0xd7e5e7FF },
        },
    },
})

-- Buttons (Lua API — not part of hl.config table for hyprbars)
local hb = hl.plugin and hl.plugin.hyprbars
if hb and type(hb.add_button) == "function" then
    hb.add_button({
        bg_color = "rgb(d7e5e7)",
        size     = 13,
        icon     = "󰖭",
        action   = "hyprctl dispatch killactive",
    })
    hb.add_button({
        bg_color = "rgb(d7e5e7)",
        size     = 13,
        icon     = "󰖯",
        action   = "hyprctl dispatch fullscreen 1",
    })
    hb.add_button({
        bg_color = "rgb(d7e5e7)",
        size     = 13,
        icon     = "󰖰",
        action   = "hyprctl dispatch movetoworkspacesilent special",
    })
end

-- windowrulev3 = bordercolor rgba(00dbecAA) rgba(00dbec77),pinned:1
hl.window_rule({
    name  = "pin-border",
    match = { pinned = true },
    border_color = { colors = { "rgba(00dbecaa)", "rgba(00dbec77)" } },
})
