-- =============================================================================
-- Colors (hyprland/colors.conf → Lua)
-- Generated by matugen from Material You palette
-- NOTE: Hyprland 0.55+ required for Lua config
--
-- Dùng chuỗi rgba() — Lua number 0x00…… bị cắt byte cao.
-- =============================================================================

-- misc.background_color (colors.conf)
hl.config({
    misc = {
        background_color = "rgba(0e141cFF)",
    },
})

-- windowrulev3 = bordercolor rgba(00dbecAA) rgba(00dbec77),pinned:1
hl.window_rule({
    name  = "pin-border",
    match = { pin = true },
    border_color = {
        colors = {
            "rgba(a6c8ffaa)",
            "rgba(a6c8ff77)",
        },
    },
})
