# general {
#     col.active_border = rgba(8093a1AA)
#     col.inactive_border = rgba(374955AA)
# }

misc {
    background_color = rgba(0b151aFF)
}

plugin {
    hyprbars {
        # Honestly idk if it works like css, but well, why not
        bar_text_font = Rubik, Geist, AR One Sans, Reddit Sans, Inter, Roboto, Ubuntu, Noto Sans, sans-serif
        bar_height = 30
        bar_padding = 10
        bar_button_padding = 5
        bar_precedence_over_border = true
        bar_part_of_window = true

        # Use a slightly elevated surface for better separation from the wallpaper/background
        bar_color = rgba(131d23FF)
        col.text = rgba(dae4ecFF)


        # example buttons (R -> L)
        # hyprbars-button = color, size, on-click
        hyprbars-button = rgb(dae4ec), 13, 󰖭, hyprctl dispatch killactive
        hyprbars-button = rgb(dae4ec), 13, 󰖯, hyprctl dispatch fullscreen 1
        hyprbars-button = rgb(dae4ec), 13, 󰖰, hyprctl dispatch movetoworkspacesilent special
    }
}

windowrulev3 = bordercolor rgba(54dbc8AA) rgba(54dbc877),pinned:1
