# general {
#     col.active_border = rgba(869395AA)
#     col.inactive_border = rgba(3c494bAA)
# }

misc {
    background_color = rgba(091517FF)
}

windowrulev3 = bordercolor rgba(00dbecAA) rgba(00dbec77),pinned:1
