-- =============================================================================
-- Colors & Hyprbars Configuration
-- Generated by matugen from Material You palette
-- NOTE: Hyprland 0.55+ required for Lua config
-- =============================================================================

hl.config({
    misc = {
        background_color = 0x091517FF,
    },
    plugin = {
        hyprbars = {
            bar_text_font    = "Rubik, Geist, AR One Sans, Reddit Sans, Inter, Roboto, Ubuntu, Noto Sans, sans-serif",
            bar_height       = 30,
            bar_padding      = 10,
            bar_button_padding = 5,
            bar_precedence_over_border = true,
            bar_part_of_window = true,
            bar_color        = 0x111e1fFF,
            col              = { text = 0xd7e5e7FF },
        },
    },
})

-- Pinned window border glow (cyan accent)
hl.window_rule({
    name = "pin-border",
    match = { pinned = true },
    bordercolor = { colors = {0x00dbecAA, 0x00dbec77} },
})

-- Floating preset sizes (exported for use in rules.lua)
local fp = {
    center_45x45   = { size = { 0.45, 0.45 } },
    center_45x55   = { size = { 0.45, 0.55 } },
    center_55x70   = { size = { 0.55, 0.70 } },
    center_60x65   = { size = { 0.60, 0.65 } },
    top_right      = { size = { 0.20, 0.50 }, move = { 0.795, 0.04 } },
    bottom_right   = { size = { 0.20, 0.50 }, move = { 0.795, 0.49 } },
}

return fp
